version: '3.8'

volumes:
  reddit_data:
    external: True

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PW
    volumes:
      - reddit_data:/data/db
    ports:
      - 27017:27017