version: '3.8'

volumes:
  reddit_data:
    external: True

  reddit_pg_data:
    external: True

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PW
    volumes:
      - reddit_data:/data/db
    ports:
      - 27017:27017

  airflow:
    container_name: reddit_scaping_airflow
    build: ./airflow
    volumes:
      - ./airflow/dags:/root/airflow/dags
      - ./airflow/airflow.cfg:/root/airflow/airflow.cfg
      - ./airflow/webserver_config.py:/root/airflow/webserver_config.py
      - ./airflow/logs:/root/airflow/logs
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres



  postgres:
    image: postgres
    volumes:
      - reddit_pg_data:/var/lib/postgresql/data
      - ./docker_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432


